dist: xenial
sudo: false

language: node_js
node_js:
  - '10'

cache:
  directories:
    - ./node_modules

install:
  - yarn install

before_deploy:
  - yarn run build -- --prod --base-href /sr-app/
  - cp dist/sr-app/index.html dist/sr-app/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/sr-app
  on:
    branch: master
