name: Test, build and Deploy
on:
  push:
    branches: [master]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: |
          sudo apt-get install xvfb
          xvfb-run --auto-servernum yarn test
      - name: Report test results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/TESTS-*.xml'
      - name: Build for GitHub pages
        run: |
          yarn build-gh-pages
          cp 404header.html dist/sr-app/404.html
          cat dist/sr-app/index.html >> dist/sr-app/404.html
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/sr-app
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
