name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build-gh-pages
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: Create 404.html
        run: |
          cp dist/sr-app/index.html dist/sr-app/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/sr-app # The folder the action should deploy.
          clean: true
